import { ɵAnimationStyleNormalizer } from '@angular/animations/browser';
import { Injectable } from '@angular/core';
import { windowTime } from 'rxjs';

@Injectable({
	providedIn: 'root'
})
export class ResidentialDataService {

	protected residential = [
		{
			name: "Altura",
			developer: "Kolte Patil",
			location: "Baner",
			specification: "3 & 4 BHK Premium Residences",
			src: "../assets/images/projects/residential/sites/Altura.png",
		},
		{
			name: "Aneesha",
			developer: "Yugal constructions and Maheshwari Developers",
			location: "Baner",
			specification: "3+BHK",
			src: "../assets/images/projects/residential/sites/Aneesha.png",
		},
		{
			name: "DND Homes",
			developer: "DND- HS Group",
			location: "Punawale",
			specification: "2BHK",
			src: "../assets/images/projects/residential/sites/DND Homes.png",
		},
		{
			name: "Kumar Peninsula",
			developer: "Kumar properties",
			location: "Baner - Pashan Link road",
			specification: "3 BHK Spacious Homes",
			src: "../assets/images/projects/residential/sites/Kumar Peninsula.png",
		},
		{
			name: "Livience Aleenta",
			developer: "Kohinoor Group, Welworth Realty & Shree Bal Developers",
			location: "Baner - Pashan Link road",
			specification: "3, 4, 4.5, 5 & 6 ",
			src: "../assets/images/projects/residential/sites/Livience Aleenta.png",
		},
		{
			name: "Serenity",
			developer: "Chandrarang developers",
			location: "Wakad",
			specification: "1 & 2 BHK",
			src: "../assets/images/projects/residential/sites/Serenity.png",
		},
		{
			name: "Suman Kunj",
			developer: "Suman Developers",
			location: "Baner-Pan Card Club Road",
			specification: "2,2.5,3BHK",
			src: "../assets/images/projects/residential/sites/Suman Kunj.JPEG",
		},
		{
			name: "FINNEZZA",
			developer: "Agrawal Raka constructions",
			location: "Pimple Saudagar",
			specification: "2 BHK Residences",
			src: "../assets/images/projects/residential/sites/FINNEZZA.png",
		},
		{
			name: "Sukhwani Skylines",
			developer: "Sukhwani Developers",
			location: "Wakad",
			specification: "2BHK, 3BHK",
			src: "../assets/images/projects/residential/sites/Sukhwani Skylines.png",
		},
		{
			name: "Sunrise Towers",
			developer: "Swaraj Homes Builders & Developer",
			location: "Nigadi",
			specification: "2BHK, 3BHK",
			src: "../assets/images/projects/residential/sites/Sunrise Towers.png",
		},
		{
			name: "Presidential Tower",
			developer: "Raviraj Realty and Govind Group",
			location: "Pimple Saudagar",
			specification: "2BHK, 3BHK",
			src: "../assets/images/projects/residential/sites/Presidential Tower.png",
		},
		{
			name: "Codename  Humanistic",
			developer: "Aryavart Developers",
			location: "Bavdhan",
			specification: "3BHK",
			src: "../assets/images/projects/residential/sites/Codename  Humanistic.png",
		},
		{
			name: "GINI Vivante",
			developer: "Gini Constructions",
			location: "Kiwale",
			specification: "2 & 3BHK",
			src: "../assets/images/projects/residential/sites/GINI Vivante.png",
		},
		{
			name: "RISING HILL",
			developer: "Badhekar Group",
			location: "Bavdhan",
			specification: "2 & 3 BHK",
			src: "../assets/images/projects/residential/sites/RISING HILL.png",
		},
		{
			name: "Vision Prisa",
			developer: "Vision Creative Group",
			location: "Ravet Pradhikaran",
			specification: "2 & 3 BHK",
			src: "../assets/images/projects/residential/sites/Vision Prisa.png",
		},
		{
			name: "Akashparv",
			developer: "Sharada Alliance Promoters and Builders",
			location: "Chandani Chowk",
			specification: "3 & 4 BHK",
			src: "../assets/images/projects/residential/sites/Akashparv.png",
		},
		{
			name: "AAIJI Crystal",
			developer: "AAIJI GROUP",
			location: "Tingre Nagar, Airport Road",
			specification: "2, 3 & 4 BHK Simplex & Duplex Residences",
			src: "../assets/images/projects/residential/sites/AAIJI Crystal.png",
		},
		{
			name: "Aryaban",
			developer: "GK Associates",
			location: "Ravet-Kiwale Road",
			specification: "3 BHK Residences",
			src: "../assets/images/projects/residential/sites/Aryaban.png",
		},
		{
			name: "Rohan Abhilasha",
			developer: "Rohan Developers",
			location: "Wagholi",
			specification: "1, 2, 3 BHK Residences",
			src: "../assets/images/projects/residential/sites/Rohan Abhilasha.png",
		},
		{
			name: "Saheel iTrend Futura",
			developer: "Saheel Developers",
			location: "Mahalunge - Baner",
			specification: "2 & 3 BHK Residences",
			src: "../assets/images/projects/residential/sites/Saheel iTrend Futura.png",
		},
		{
			name: "Pushkar",
			developer: "Badhekar Group",
			location: "Kothrud, Bhusari",
			specification: "2 & 3 BHK Residences",
			src: "../assets/images/projects/residential/sites/Pushkar.png",
		},
		{
			name: "Rohan Ekam",
			developer: "Rohan Developers",
			location: "Balewadi",
			specification: "2, 3, 4 BHK & Duplex Residences",
			src: "../assets/images/projects/residential/sites/Rohan Ekam.png",
		},
		{
			name: "Purva Aspire",
			developer: "Purvankara Developers",
			location: "Bavdhan",
			specification: "2, 3BHK Residences",
			src: "../assets/images/projects/residential/sites/Purva Aspire.png",
		},
		{
			name: "Solitaire Business HUB",
			developer: "Solitaire Developers",
			location: "Baner",
			specification: "Commercial Showrooms & Office space",
			src: "../assets/images/projects/residential/sites/Solitaire Business HUB.jpg",
		},
		{
			name: "45 BANER STREET",
			developer: "Raichandani Group",
			location: "Baner",
			specification: "Commercial Showrooms & Office space",
			src: "../assets/images/projects/residential/sites/45 BANER STREET.png",
		},
		{
			name: "Ra Urbania",
			developer: "Croissance Group",
			location: "Ravet",
			specification: "2 & 3 BHK Residences",
			src: "../assets/images/projects/residential/sites/Ra Urbania.png",
		},
		{
			name: "57 Elevate",
			developer: "Aishwaryam Group, Sanskruti Developers, Avneesh Realty",
			location: "Wakad",
			specification: "3 BHK Residences",
			src: "../assets/images/projects/residential/sites/57 Elevate.png",
		},
		{
			name: "BELLA ROSSA PHASE-2",
			developer: "VEDDANT BUILDCON",
			location: "Wakad",
			specification: "2 & 3 BHK Residences",
			src: "../assets/images/projects/residential/sites/BELLA ROSSA PHASE-2.png",
		},
		{
			name: "Treasure Troves",
			developer: "Siddhashila group and SSD group",
			location: "Wakad",
			specification: "2 & 3 BHK Residences",
			src: "../assets/images/projects/residential/sites/Treasure Troves.jpeg",
		},
		{
			name: "ANP Universe",
			developer: "ANP Corp",
			location: "Balewadi High Street",
			specification: "3 & 4 BHK Residences",
			src: "../assets/images/projects/residential/sites/ANP Universe.png",
		},
		{
			name: "Supreme ESTIA",
			developer: "Supreme Universal",
			location: "Baner - Pancard Club",
			specification: "2, 3 and 4 BHK residences",
			src: "../assets/images/projects/residential/sites/Supreme ESTIA.png",
		},
		{
			name: "Majestique ORNATE",
			developer: "Majestique Landmark",
			location: "Baner",
			specification: "3 & 4 BHK residences",
			src: "../assets/images/projects/residential/sites/Majestique ORNATE.png",
		},
		{
			name: "Majestique 27 GRAND",
			developer: "Majestique Landmark",
			location: "2 & 3 BHK residences",
			specification: "Balewadi",
			src: "../assets/images/projects/residential/sites/Majestique 27 GRAND.png",
		},
		{
			name: "Majestique Signature Towers",
			developer: "Majestique Landmark",
			location: "Balewadi",
			specification: "2 & 3 BHK residences",
			src: "../assets/images/projects/residential/sites/Majestique Signature Towers.png",
		},
		{
			name: "GRANDEZA",
			developer: "Padale Group",
			location: "SUS",
			specification: "1 & 2 BHK residences",
			src: "../assets/images/projects/residential/sites/GRANDEZA.png",
		},
		{
			name: "KIRAN SAMRUDDHI",
			developer: "KIRAN Creators Group",
			location: "Pashan - SUS Road",
			specification: "1 & 2 BHK residences",
			src: "../assets/images/projects/residential/sites/KIRAN SAMRUDDHI.png",
		},
		{
			name: "LA - MODA",
			developer: "Manav Group",
			location: "Balewadi",
			specification: "2 & 3 BHK residences",
			src: "../assets/images/projects/residential/sites/LA - MODA.png",
		},
		{
			name: "Mahindra Life Space",
			developer: "Mahindra Group",
			location: "Pimpri Colony, PCMC",
			specification: "2 & 3 BHK residences",
			src: "../assets/images/projects/residential/sites/Mahindra Life Space.png",
		},
		{
			name: "Shivatman",
			developer: "Naiknavare Developers",
			location: "Shivajinagar",
			specification: "2 & 3 BHK residences",
			src: "../assets/images/projects/residential/sites/Shivatman.png",
		},
		{
			name: "Joywood",
			developer: "Project by Menlo",
			location: "Bavdhan",
			specification: "2 & 3 BHK residences",
			src: "../assets/images/projects/residential/sites/Joywood.png",
		},
		{
			name: "Ambrosia alley",
			developer: "Ambrosia Landmarks",
			location: "Hadapsar",
			specification: "1 & 2 BHK Residences",
			src: "../assets/images/projects/residential/sites/Ambrosia alley.png",
		},
		{
			name: "ECO Homes",
			developer: "Kasturi Developers",
			location: "Hinjewadi",
			specification: "2 & 3 BHK Residences",
			src: "../assets/images/projects/residential/sites/ECO Homes.png",
		},
		{
			name: "Alpine Astonia",
			developer: "Alpine Landmarks",
			location: "Ravet-Kiwale",
			specification: "2 & 3 BHK Residences",
			src: "../assets/images/projects/residential/sites/Alpine Astonia.png",
		},
		{
			name: "Hermosa Casa",
			developer: "Sukhwani Developers",
			location: "Mundhwa - Kharadi Rd",
			specification: "2, 2.5, & 3 BHK Residences",
			src: "../assets/images/projects/residential/sites/Aneesha.png",
		},
		{
			name: "Teerth Avila",
			developer: "Teerth Realties",
			location: "SUS",
			specification: "2.5 BHK Residences",
			src: "../assets/images/projects/residential/sites/Teerth Avila.png",
		},
		{
			name: "Kumar Paradise",
			developer: "Kumar Properties",
			location: "Near Margarpatta",
			specification: "2 BHK Residences",
			src: "../assets/images/projects/residential/sites/Kumar Paradise.png",
		},
		{
			name: "97 Sepia",
			developer: "Sukhwani Developers",
			location: "Wakad",
			specification: "2 & 3 BHK Residences",
			src: "../assets/images/projects/residential/sites/97 Sepia.JPEG",
		},
		{
			name: "Sukhwani Skyline",
			developer: "Sukhwani Developers",
			location: "Wakad",
			specification: "2 & 3 BHK Residences",
			src: "../assets/images/projects/residential/sites/Aneesha.png",
		},
		{
			name: "Songs from the Woods",
			developer: "Total Environment developers",
			location: "Uday Baug",
			specification: "3 & 4 BHK Residences",
			src: "../assets/images/projects/residential/sites/Songs from the Woods.png",
		},
		{
			name: "Sukhwani Kingsley",
			developer: "Sukhwani Developers",
			location: "Wakad Annex, Thergaon",
			specification: "2 BHK Residences",
			src: "../assets/images/projects/residential/sites/Sukhwani Kingsley.png",
		},
		{
			name: "La Centra",
			developer: "Manav Group",
			location: "Wakad - Tathawade",
			specification: "2 BHK Residences",
			src: "../assets/images/projects/residential/sites/La Centra.png",
		},
		{
			name: "Nyati Elite",
			developer: "Nyati",
			location: "Undri",
			specification: "3 & 4.5 BHK residences",
			src: "../assets/images/projects/residential/sites/Nyati Elite.png",
		},
		{
			name: "Vertillas",
			developer: "Spectrum Properties",
			location: "Kharadi",
			specification: "2 & 3 BHK residences",
			src: "../assets/images/projects/residential/sites/Vertillas.png",
		},
		{
			name: "Samrajya",
			developer: "Garve-Patil Constructions",
			location: "New Sangvi",
			specification: "2 & 3 BHK residences",
			src: "../assets/images/projects/residential/sites/Samrajya.png",
		},
		{
			name: "Rohan Nidita",
			developer: "Rohan Developers",
			location: "Hinjewadi",
			specification: "2 & 3 BHK residences",
			src: "../assets/images/projects/residential/sites/Rohan Nidita.png",
		},
		// {
		// 	name: "",
		// 	developer: "",
		// 	location: "",
		// 	specification: "",
		// 	src: "../assets/images/projects/residential/sites/Aneesha.png",
		// },
	]

	getResidentialDataService() {
		return this.residential;
	}
}
